name = "stone-web"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"

# 必须启用 assets 配置，否则 CSS 和图片无法加载
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[build]
# 这里确保远程构建时使用的是 opennext 的打包逻辑
command = "npx @opennextjs/cloudflare build"

# 删掉原本的 [[services]] 和 [build.upload]，OpenNext 不需要这些